<?php

/**
 * @file
 * EBay commerce user module.
 */

/**
 * Implements hook_menu().
 */
function ebay_commerce_user_menu() {
  $items = array();

  /* Development Menu */

  $items['admin/ebay/user'] = array(
    'title' => 'User',
    'description' => 'eBay user information.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer ebay'),
    'type' => MENU_NORMAL_ITEM,
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => 49,
  );

  $items['admin/ebay/user/profile'] = array(
    'title' => 'Profile',
    'description' => 'Your eBay user details.',
    'page callback' => 'ebay_commerce_user_page_profile',
    'access arguments' => array('administer ebay'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
  );

  return $items;

}

/**
 * Page callback sets up and returns the content for the Page.
 */
function ebay_commerce_user_page_profile() {

  $ebay_commerce_user = ebay_commerce_get_user();

  $ebay_commerce_user_settings = array(
    'mode' => EBAY_COMMERCE_MODE,
    'api' => EBAY_COMMERCE_API,
    'site' => EBAY_COMMERCE_SITE,
    'currency' => EBAY_COMMERCE_CURRENCY,
    'language' => EBAY_COMMERCE_ERROR_LANGUAGE,
    'warning-level' => EBAY_COMMERCE_WARNING_LEVEL,
    'tracking' => EBAY_COMMERCE_INVENTORY_TRACKING,
    'developer-id' => EBAY_COMMERCE_DEVELOPER_ID,
    'application-id' => EBAY_COMMERCE_APPLICATION_ID,
    'cert-id' => EBAY_COMMERCE_CERT_ID,
    'url' => EBAY_COMMERCE_SERVER_URL,
    'token' => EBAY_COMMERCE_USER_TOKEN,
    'paypal' => EBAY_COMMERCE_USER_PAYPAL,
  );

  return theme('ebay_commerce_user', array(
    'ebay_user' => $ebay_commerce_user,
    'ebay_user_settings' => $ebay_commerce_user_settings,
  ));

}

/**
 * Implements hook_theme().
 */
function ebay_commerce_user_theme() {
  return array(
    'ebay_commerce_user' => array(
      'variables' => array(
        // Specifies available variables.
        'ebay_user' => NULL,
        'ebay_user_settings' => NULL,
      ),
      // This allows you to create a tpl file
      // ebay_commerce_user_profile.tpl.php.
      'template' => 'ebay_commerce_user_profile',
    ),
  );
}
