<?php

/**
 * @file
 *
 * Load values from eBay and insert them in the database.
 *
 * - Country/site information.
 */


/**
 * Connect to eBay and retrieves the current list of
 * eBay sites and their Site ID values.
 *
 */

function ebay_commerce_load_sites_ebay(){

  $requestXmlBody = '<DetailName>SiteDetails</DetailName>';
  $record = ebay_commerce_action('GeteBayDetails', $requestXmlBody);

  if($record){
    foreach ($record as $value) {
      $responses = $value->getElementsByTagName('SiteDetails');

        foreach ($responses as $response) {

          $variable = $response->getElementsByTagName('Site');
          $site = $variable->item(0)->nodeValue;

          $variable = $response->getElementsByTagName('SiteID');
          $site_id = $variable->item(0)->nodeValue;

          $ebay[$site_id] = array(
            'site' => $site,
            'site_id' => $site_id,
          );
        }
    }
   return $ebay;
  }
}

/**
 * Insert eBay site information in the database.
 * Table : ebay_commerce_sites.
 */
function ebay_commerce_save_sites_db() {

  $values = ebay_commerce_load_sites_ebay();

  foreach ($values as $key => $value) {

    $query = db_merge('ebay_commerce_sites')
     ->key(array('site_id' => $values[$key]['site_id']))
     ->fields((array)$values[$key]);

    try{ $query->execute(); }
    catch(Exception $e){ drupal_set_message( $e->getMessage()); }
  }

}

/**
 * Load ebay sites from the database.
 *
 * @code
 * $result = ebay_commerce_load_sites_db();
 *   foreach ($result as $record) {
 *     dsm($record);
 *   }
 * @endcode
 *
 */
function ebay_commerce_load_sites_db(){

  $query=db_select('ebay_commerce_sites', 'a')
   ->fields('a',array('site_id', 'site'));
  $result= $query->execute();
  return $result;

}
